//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_TicketPremium.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PARTIDO_FUTBOL", Namespace="http://schemas.datacontract.org/2004/07/federacionFutbol")]
    [System.SerializableAttribute()]
    public partial class PARTIDO_FUTBOL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EQUIPO_LOCALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EQUIPO_VISITAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LUGARField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CODIGO {
            get {
                return this.CODIGOField;
            }
            set {
                if ((this.CODIGOField.Equals(value) != true)) {
                    this.CODIGOField = value;
                    this.RaisePropertyChanged("CODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EQUIPO_LOCAL {
            get {
                return this.EQUIPO_LOCALField;
            }
            set {
                if ((object.ReferenceEquals(this.EQUIPO_LOCALField, value) != true)) {
                    this.EQUIPO_LOCALField = value;
                    this.RaisePropertyChanged("EQUIPO_LOCAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EQUIPO_VISITA {
            get {
                return this.EQUIPO_VISITAField;
            }
            set {
                if ((object.ReferenceEquals(this.EQUIPO_VISITAField, value) != true)) {
                    this.EQUIPO_VISITAField = value;
                    this.RaisePropertyChanged("EQUIPO_VISITA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHA {
            get {
                return this.FECHAField;
            }
            set {
                if ((this.FECHAField.Equals(value) != true)) {
                    this.FECHAField = value;
                    this.RaisePropertyChanged("FECHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LUGAR {
            get {
                return this.LUGARField;
            }
            set {
                if ((object.ReferenceEquals(this.LUGARField, value) != true)) {
                    this.LUGARField = value;
                    this.RaisePropertyChanged("LUGAR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Iservice")]
    public interface Iservice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iservice/Partidos", ReplyAction="http://tempuri.org/Iservice/PartidosResponse")]
        Client_TicketPremium.ServiceReference1.PARTIDO_FUTBOL[] Partidos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iservice/Partidos", ReplyAction="http://tempuri.org/Iservice/PartidosResponse")]
        System.Threading.Tasks.Task<Client_TicketPremium.ServiceReference1.PARTIDO_FUTBOL[]> PartidosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IserviceChannel : Client_TicketPremium.ServiceReference1.Iservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IserviceClient : System.ServiceModel.ClientBase<Client_TicketPremium.ServiceReference1.Iservice>, Client_TicketPremium.ServiceReference1.Iservice {
        
        public IserviceClient() {
        }
        
        public IserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client_TicketPremium.ServiceReference1.PARTIDO_FUTBOL[] Partidos() {
            return base.Channel.Partidos();
        }
        
        public System.Threading.Tasks.Task<Client_TicketPremium.ServiceReference1.PARTIDO_FUTBOL[]> PartidosAsync() {
            return base.Channel.PartidosAsync();
        }
    }
}
