//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPremium_SOAP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEDEF_DETFAC
    {
        public int TEFAC_CODIGO { get; set; }
        public string TELCP_CODIGO { get; set; }
        public string TEPAF_CODIGO { get; set; }
        public int TEDEF_CANTID { get; set; }
        public double TEDEF_SUBTOT { get; set; }
    
        public virtual TEFAC_FACTUR TEFAC_FACTUR { get; set; }
        public virtual TELCP_LOCPTD TELCP_LOCPTD { get; set; }
    }
}
