//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPremium_SOAP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEFAC_FACTUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEFAC_FACTUR()
        {
            this.TEDEF_DETFAC = new HashSet<TEDEF_DETFAC>();
        }
    
        public int TEFAC_CODIGO { get; set; }
        public string TECLI_CODIGO { get; set; }
        public System.DateTime TEFAC_FECHA { get; set; }
        public string TEFAC_MODPAG { get; set; }
        public double TEFAC_TOTAL { get; set; }
    
        public virtual TECLI_CLIENT TECLI_CLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEDEF_DETFAC> TEDEF_DETFAC { get; set; }
    }
}
