//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPremium_SOAP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELCP_LOCPTD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TELCP_LOCPTD()
        {
            this.TEDEF_DETFAC = new HashSet<TEDEF_DETFAC>();
        }
    
        public string TELCP_CODIGO { get; set; }
        public string TEPAF_CODIGO { get; set; }
        public int TELCP_DISPON { get; set; }
        public double TELCP_PRECIO { get; set; }
        public int TELCP_CANBAS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEDEF_DETFAC> TEDEF_DETFAC { get; set; }
        public virtual TEPAF_PARFUT TEPAF_PARFUT { get; set; }
    }
}
