//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPremium_SOAP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEPAF_PARFUT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEPAF_PARFUT()
        {
            this.TELCP_LOCPTD = new HashSet<TELCP_LOCPTD>();
        }
    
        public string TEPAF_CODIGO { get; set; }
        public string TEPAF_LOCAL { get; set; }
        public string TEPAF_VISITA { get; set; }
        public System.DateTime TEPAF_FECHA { get; set; }
        public string TEPAF_LUGAR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TELCP_LOCPTD> TELCP_LOCPTD { get; set; }
    }
}
